### ISSUE TITLE
Help with installation needed

### ISSUE THREAD

**Issue by totoroot** [utdemir/dotfiles#68]
Hey there,

I stumbled across your dotfiles and since we have a similar taste in software I thought about giving your setup a try first and modify it later on to suit my needs, but since this is my first venture into the NixOS cosmos, I did not get very far and could need some help...

According to your installation steps one should simply install NixOS. I chose the minimal image and installed it according to the instructions in the NixOS manual. I ran the default configuration, logged in as root and cloned the forked repo in which I had already modified "user.nix". Then I removed your hardware configuration from "hardware.nix" and added mine from the generated hardware config.

My first problem was, that I didn't know what to make of this part of your installation instructions:
`cp home-private.nix{.example,}; cp system-private.nix{.example,}`
So I skipped that part and tried running:
`./make.sh switch`

It failed with:
`error: unrecognised flag '--experimental features'`

I noticed that flakes were not installed and read that they were only installed in the unstable version of Nix so I added this
```nix
{ pkgs, ... }: {
   nix = {
    package = pkgs.nixFlakes;
    extraOptions = ''
      experimental-features = nix-command flakes
    '';
   };
}
```
to my "configuration.nix" and ran nixos-rebuild switch.

That worked and I tried running your script which again failed with something along the lines of this
```bash
! sudo nix-os rebuild switch --flake .
Building the system configuration...
error: --- Error -------------------------------------------------------------------------------------------------
flake 'git+file:///dotfiles' does not provide attribute 'packages.x86_64-linux.nixosConfigurations."nixos".config.system.build.toplevel', 'legacyPackages.x86_64-linux.nixosConfigurations."nixos".config.system.build.toplevel' or 'nixosConfigurations."nixos".config.system.build.toplevel'
```

Do you have any idea what might have caused it to fail and if the part I skipped was crucial, what exactly I have to do to accomplish this and in order to get your configuration to work properly?

Cheers and many thanks in advance!

**Comment by utdemir** [comment]
Hey, I am glad you find this interesting! And thank you for sharing your fixes, I'll update the README (all your fixes make sense to me). I recently moved the configuration to flakes but did not try a fresh installation, so the instructions aren't great, sorry about that!

I think the `nixos-rebuild switch --flake .` requires the exported attribute from our flake.nix to match your computers hostname. So, maybe setting `hostname` to your hostname (`nixos` in your case, I think) would help. Also there was a way to make it a look a different attribute but I can not remember it.

Let me know if it works or not.

**Comment by cipharius** [comment]
I'm also having tough time with a fresh build.

I managed to resolve the hostname issue by removing quotes around hostname substitution in `flake.nix` (now it looks like: `nixosConfigurations.${(import ./user.nix).hostname}`).

Besides this, `*-private.nix` files don't get copied over to nix store, so for now I removed them from configuration. It's as if flakes cloned the repository files, thus respecting gitignore.

**Comment by utdemir** [comment]
@cipharius Thank you for the comment.

I updated the installation instructions to:

* Mention that the system hostname and the hostname defined in `user.nix` should be the same. This was the issue both mentioned in @totoroot and @cipharius 's comments.
* Remove the note about `*-private.nix` files as they are committed to the repository (from @cipharius 's comment).
* Mention that we should use `pkgs.nixFlakes` (@totoroot 's comment)

WIth those modifications, I was able to install it to a virtual machine. 

I'd be glad if you look at the new instructions and let me know if they are adequate. Or please tell me (or send a PR) if you think anything else to make this process smoother. The main issue is that I'm not reinstalling my system often and the installation instructions diverge as I modify the repository, and comments like these are the only way I can notice the installation issues.

**Comment by totoroot** [comment]
Thanks for updating your repo!
By now I've tested it in a VM too and can confirm that it did work indeed.
However, I used another repo as a starting point for my system configuration and have already modified according to my taste, such that it is usable as a daily driver by now.
Thanks again!!
